/*
 * The Machine — an offline voice assistant for Android.
 * Copyright (C) 2026 Hasan Ismail
 *
 * This program is free software: you can redistribute it and/or modify it under
 * the terms of the GNU Affero General Public License as published by the Free
 * Software Foundation, either version 3 of the License, or (at your option) any
 * later version. See the LICENSE file in the project root for the full text.
 */
package io.github.hasanismail.themachine.audio

import android.media.AudioAttributes
import android.media.AudioFormat
import android.media.AudioTrack
import androidx.annotation.VisibleForTesting
import kotlin.math.PI
import kotlin.math.exp
import kotlin.math.sin
import kotlin.math.sqrt

/**
 * Interface cues, synthesised from scratch at runtime.
 *
 * Every waveform here is generated by the code below — there are no audio assets in
 * this project and none are downloaded. That is partly the privacy/attribution
 * position in the README, and partly practical: these are a few hundred bytes of
 * arithmetic instead of megabytes of WAV, and a cue can be retuned by changing a
 * number rather than re-recording.
 *
 * The palette is deliberately small and short. Cues under ~200 ms read as a machine
 * acknowledging something; anything longer starts to feel like a notification sound.
 */
object MachineSounds {

    const val SAMPLE_RATE = 44_100

    /** Fade applied to both ends of every cue; without it each one starts with a pop. */
    private const val RAMP_MILLIS = 2

    /** Square/sine blend in [click]. Mostly square, for an edge. */
    private const val CLICK_SQUARE_MIX = 0.6
    private const val CLICK_SINE_MIX = 0.4
    private const val CLICK_GAIN = 0.7

    /** Peak amplitude of [sweep], left below full scale so the mix never clamps. */
    private const val SWEEP_GAIN = 0.9

    private const val MILLIS_PER_SECOND = 1000

    /** The cues the interface can emit. */
    enum class Cue {
        /** A single dry click. Focus moves, a value ticks. */
        TICK,

        /** Rising two-tone. Capture has started, the system is listening. */
        ENGAGE,

        /** Falling two-tone. Capture ended, input accepted. */
        DISENGAGE,

        /** Bright triad. An action completed successfully. */
        CONFIRM,

        /** Low buzz. Refused, unsupported, or failed. */
        REJECT,

        /** Slow sweep upward. Cold start / first frame of the interface. */
        BOOT,
    }

    private val trackLock = Any()
    private val cache = HashMap<Cue, ShortArray>()

    /**
     * Renders [cue] to 16-bit mono PCM. Pure and deterministic, which is what makes
     * the waveforms unit-testable without a device.
     */
    @VisibleForTesting
    fun render(cue: Cue): ShortArray = when (cue) {
        Cue.TICK -> click(durationMs = 18, frequency = 2100.0, decay = 90.0)

        Cue.ENGAGE -> sequence(
            tone(durationMs = 55, frequency = 660.0, decay = 14.0),
            tone(durationMs = 90, frequency = 990.0, decay = 11.0),
        )

        Cue.DISENGAGE -> sequence(
            tone(durationMs = 55, frequency = 880.0, decay = 14.0),
            tone(durationMs = 90, frequency = 587.0, decay = 11.0),
        )

        Cue.CONFIRM -> sequence(
            tone(durationMs = 45, frequency = 784.0, decay = 16.0),
            tone(durationMs = 45, frequency = 1046.0, decay = 16.0),
            tone(durationMs = 120, frequency = 1568.0, decay = 9.0),
        )

        Cue.REJECT -> sequence(
            tone(durationMs = 90, frequency = 196.0, decay = 9.0, harmonic = 0.5),
            tone(durationMs = 140, frequency = 147.0, decay = 7.0, harmonic = 0.5),
        )

        Cue.BOOT -> sweep(durationMs = 620, fromHz = 180.0, toHz = 1320.0)
    }

    /**
     * Plays [cue]. Cheap enough to call from a composable's side effect: the PCM is
     * rendered once per cue and cached, and playback is fire-and-forget on a
     * short-lived static AudioTrack that releases itself when it finishes.
     */
    fun play(cue: Cue, volume: Float = 0.55f) {
        val pcm = synchronized(trackLock) { cache.getOrPut(cue) { render(cue) } }
        val bytes = pcm.size * 2
        val track = AudioTrack.Builder()
            .setAudioAttributes(
                AudioAttributes.Builder()
                    // SONIFICATION, not NOTIFICATION: these are interface feedback and
                    // should follow the media/alarm stream behaviour rather than pop up
                    // as if the app were notifying the user of something.
                    .setUsage(AudioAttributes.USAGE_ASSISTANCE_SONIFICATION)
                    .setContentType(AudioAttributes.CONTENT_TYPE_SONIFICATION)
                    .build(),
            )
            .setAudioFormat(
                AudioFormat.Builder()
                    .setEncoding(AudioFormat.ENCODING_PCM_16BIT)
                    .setSampleRate(SAMPLE_RATE)
                    .setChannelMask(AudioFormat.CHANNEL_OUT_MONO)
                    .build(),
            )
            .setTransferMode(AudioTrack.MODE_STATIC)
            .setBufferSizeInBytes(bytes)
            .build()

        track.write(pcm, 0, pcm.size)
        track.setVolume(volume.coerceIn(0f, 1f))
        track.setNotificationMarkerPosition(pcm.size)
        track.setPlaybackPositionUpdateListener(
            object : AudioTrack.OnPlaybackPositionUpdateListener {
                override fun onMarkerReached(t: AudioTrack) {
                    t.release()
                }

                override fun onPeriodicNotification(t: AudioTrack) = Unit
            },
        )
        track.play()
    }

    // ---- Synthesis ---------------------------------------------------------------

    private fun samples(durationMs: Int) = SAMPLE_RATE * durationMs / MILLIS_PER_SECOND

    /**
     * An exponentially decaying sine. [decay] is in nepers per second — higher means
     * a shorter, drier sound. [harmonic] mixes in an octave below at that gain, which
     * is what gives REJECT its weight.
     */
    private fun tone(
        durationMs: Int,
        frequency: Double,
        decay: Double,
        harmonic: Double = 0.0,
    ): ShortArray {
        val n = samples(durationMs)
        val out = ShortArray(n)
        for (i in 0 until n) {
            val t = i.toDouble() / SAMPLE_RATE
            val envelope = exp(-decay * t) * attack(i, n)
            var v = sin(2 * PI * frequency * t)
            if (harmonic > 0.0) {
                v += harmonic * sin(PI * frequency * t)
            }
            out[i] = clip(v * envelope / (1.0 + harmonic))
        }
        return out
    }

    /** A very short burst of noise-free high tone: reads as a mechanical click. */
    private fun click(durationMs: Int, frequency: Double, decay: Double): ShortArray {
        val n = samples(durationMs)
        val out = ShortArray(n)
        for (i in 0 until n) {
            val t = i.toDouble() / SAMPLE_RATE
            // Square-ish rather than pure sine so it has an edge to it.
            val square = if (sin(2 * PI * frequency * t) >= 0) 1.0 else -1.0
            val shaped = CLICK_SQUARE_MIX * square + CLICK_SINE_MIX * sin(2 * PI * frequency * t)
            out[i] = clip(shaped * exp(-decay * t) * attack(i, n) * CLICK_GAIN)
        }
        return out
    }

    /** Log-frequency sweep with a gentle bell envelope. */
    private fun sweep(durationMs: Int, fromHz: Double, toHz: Double): ShortArray {
        val n = samples(durationMs)
        val out = ShortArray(n)
        var phase = 0.0
        for (i in 0 until n) {
            val progress = i.toDouble() / n
            // Sweeping the log of frequency keeps the rise perceptually even.
            val f = fromHz * Math.pow(toHz / fromHz, progress)
            phase += 2 * PI * f / SAMPLE_RATE
            // Rise quickly, hold, fall away.
            val envelope = sqrt(progress).coerceAtMost(1.0) * (1.0 - progress * progress)
            out[i] = clip(sin(phase) * envelope * SWEEP_GAIN)
        }
        return out
    }

    /** Linear fade of [RAMP_MILLIS] at each end. */
    private fun attack(index: Int, total: Int): Double {
        val ramp = (SAMPLE_RATE * RAMP_MILLIS / MILLIS_PER_SECOND)
            .coerceAtMost(total / 2)
            .coerceAtLeast(1)
        val rise = (index.toDouble() / ramp).coerceAtMost(1.0)
        val fall = ((total - index).toDouble() / ramp).coerceAtMost(1.0)
        return rise * fall
    }

    private fun sequence(vararg parts: ShortArray): ShortArray {
        val out = ShortArray(parts.sumOf { it.size })
        var offset = 0
        for (part in parts) {
            part.copyInto(out, offset)
            offset += part.size
        }
        return out
    }

    private fun clip(v: Double): Short =
        (v.coerceIn(-1.0, 1.0) * Short.MAX_VALUE).toInt().toShort()
}
